config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :authors
  root :to => "recipes#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :author

  def self.search(search)
    if search
      where('name LIKE ? OR main_ingredient LIKE ?', "%#{search}%","%#{search}%")
    else
      Recipe.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :rating, :link, :search, :sort)
    end

  private
  def sort_column
    Author.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes= Recipe.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end
  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :author_id, :image, :cook_time, :geography, :main_ingredient, :dish_type, :link,:search, :sort)
    end

  private
  def sort_column
    Recipe.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, request.params.merge(sort: column, direction: direction, page: nil)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_area :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>
<p>Total number of authors <%= @authors.total_entries %><br>
  Authors per page <%= @authors.length %></p>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sortable "name", "Name" %></th>
      <th><%= sortable "rating", "Rating" %></th>
      <th>Link</th>
      <th>Number of recipes</th>
<!--      <th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.rating %></td>
        <td><%= link_to "Link to site",author.link %></td>
        <td><%= author.recipe.ids.length %></td>
<!--        <td><%#= link_to 'Show', author %></td>-->
<!--        <td><%#= link_to 'Edit', edit_author_path(author) %></td>-->
<!--        <td><%#= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @authors , renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
<%#= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @author.rating %>
</p>

<p>
  <strong>Link:</strong>
  <%= @author.link %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My app for recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="recipes#index">Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="authors#index">Authors</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
  <body>
    <%= yield %>
  </body>
  </div>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="field">
    <%= form.label :cook_time %>
    <%= form.text_area :cook_time %>
  </div>

  <div class="field">
    <%= form.label :geography %>
    <%= form.text_area :geography %>
  </div>

  <div class="field">
    <%= form.label :main_ingredient %>
    <%= form.text_area :main_ingredient %>
  </div>

  <div class="field">
    <%= form.label :dish_type %>
    <%= form.text_area :dish_type %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_area :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipes.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="table table-striped table-bordered table-condensed " >
  <thead>
  <tr>
    <th style="width: 30%"><%= sortable "name", "Name"%></th>
    <th style="width: 10%">Author</th>
    <!--      <th style="width: 5%">Image</th>-->
    <th style="width: 10%">Cook time</th>
    <th style="width: 10%"><%= sortable "geography", "Geography"%></th>
    <th style="width: 15%"><%= sortable "main_ingredient", "Main ingredient"%></th>
    <th style="width: 10%"><%= sortable "dish_type", "Dish type"%></th>
    <th style="width: 10%">Link</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= link_to "#{recipe.author.name}",recipe.author %></td>
      <!--        <td><%#= link_to "Image", recipe.image %></td>-->
      <td><%= recipe.cook_time %></td>
      <td><%= recipe.geography %></td>
      <td><%= recipe.main_ingredient %></td>
      <td><%= recipe.dish_type %></td>
      <td><%= link_to "Link to site", recipe.link %></td>
      <td><%= link_to 'Show', recipe %></td>
      <!--        <td><%#= link_to 'Edit', edit_recipe_path(recipe) %></td>-->
      <!--        <td><%#= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= will_paginate @recipes, renderer: WillPaginate::ActionView::BootstrapLinkRenderer  %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>
<p>Total number of recipes <%= @recipes.total_entries %><br>
   Recipes per page <%= @recipes.length %></p>

<%= form_tag recipes_path, :method => 'get', :id => "recipes_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="recipes">
    <%= render "recipes" %>
  </div>

<% end %>



<%#= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/index.js.erb
$('#recipes').html('<%= escape_javascript(render partial:'recipes') %>');

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @recipe.author.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @recipe.image, size: "400x300" %>
</p>

<p>
  <strong>Cook time:</strong>
  <%= @recipe.cook_time %>
</p>

<p>
  <strong>Geography:</strong>
  <%= @recipe.geography %>
</p>

<p>
  <strong>Main ingredient:</strong>
  <%= @recipe.main_ingredient %>
</p>

<p>
  <strong>Dish type:</strong>
  <%= @recipe.dish_type %>
</p>

<p>
  <strong>Link:</strong>
  <%= link_to @recipe.link %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>